# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: create-actions-runner-instance
on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: Image Tag
        required: false
        default: latest
defaults:
  run:
    shell: bash -ex {0} # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#custom-shell
jobs:
  create-actions-runner-infrastructure:
    if: contains("richardsnider", github.actor)
    runs-on: ubuntu-latest
    steps:
      - id: github-cli
        run: | # https://docs.github.com/en/rest/reference/actions#create-a-registration-token-for-an-organization
          gh --version
          export RUNNER_ORG_REGISTRATION_TOKEN=$(gh api /orgs/${{ repository.owner }}/actions/runners/registration-token)
          docker run \
          --env AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          --env AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          --env AWS_DEFAULT_REGION=us-west-2 \
          --env RUNNER_ORG_REGISTRATION_TOKEN=$RUNNER_ORG_REGISTRATION_TOKEN
          --tty \
          --interactive \
          cloud-infrastructure \
          node source/create-runner-infrastructure.js
