# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
# https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
name: k3s # https://github.com/k3s-io/k3s
on:
  workflow_dispatch:
    inputs: # https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context
      manual-workflow-trigger-comment:
        required: false
        default: manual workflow_dispatch triggered
        description: comment
      force-cache-update:
        default: false
        required: false
        type: boolean
        description: force-cache-update
defaults:
  run:
    shell: bash -ex {0} # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#custom-shell
jobs:
  create-cluster:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      AWS_DEFAULT_REGION: us-west-2 # Oregon
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - id: checkout
        uses: actions/checkout@v2 # https://github.com/actions/checkout/blob/main/action.yml
      - id: tailscale
        uses: tailscale/github-action@v1 # https://github.com/tailscale/github-action/blob/main/action.yml
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - id: tailscale-post-setup
        name: Tailscale Post Setup
        run: |
          echo "TAILSCALE_IP=$(tailscale ip -4)" >> $GITHUB_ENV
          sudo useradd k3s
          (echo '${{ secrets.K3S_USER_PASSWORD }}'; echo '${{ secrets.K3S_USER_PASSWORD }}') | sudo passwd k3s
          sudo usermod -a -G sudo k3s
      - id: cache
        uses: actions/cache@v3 # https://github.com/actions/cache/blob/main/action.yml
        with:
          path: |
            /usr/local/bin/k3s
            /usr/local/bin/litestream
          key: k3s
      - id: download-k3s
        name: Download k3s
        if: steps.cache.outputs.cache-hit != 'true' || inputs.force-cache-update
        run: | # https://rancher.com/docs/k3s/latest/en/installation/install-options/
          sudo curl -o /usr/local/bin/k3s -sL https://github.com/k3s-io/k3s/releases/latest/download/k3s
          sudo chmod +x /usr/local/bin/k3s
          sudo k3s --version
      - id: download-litestream
        name: Download litestream
        if: steps.cache.outputs.cache-hit != 'true' || inputs.force-cache-update
        run: | # https://litestream.io/install/debian/
          gh release download --repo https://github.com/benbjohnson/litestream --pattern '*-linux-amd64.deb' --dir litestream.deb
          sudo dpkg --install  --instdir=/usr/local/bin litestream.deb
          sudo litestream --version
      - id: set-dns
        name: Set DNS
        env:
          DNS_RECORD_SET_CHANGE_BATCH_JSON: >
            {
              "Changes": [{
                "Action": "UPSERT",
                "ResourceRecordSet": {
                  "Name": "k3s-gh.vorprog.com",
                  "Type": "A",
                  "TTL": 300,
                  "ResourceRecords": [{ "Value": "${{ env.TAILSCALE_IP }}" }]
                }
              }]
            }
        run: |
          aws route53 change-resource-record-sets \
          --hosted-zone-id ${{ secrets.AWS_HOSTED_ZONE_ID_VORPROG }} \
          --change-batch "$DNS_RECORD_SET_CHANGE_BATCH_JSON"
      - id: start-cluster
        name: Start Cluster
        timeout-minutes: 1
        env:
          AWS_CREDENTIALS_SECRET_RESOURCE: | # https://kubernetes.io/docs/concepts/configuration/secret/
            kind: Secret
            apiVersion: v1
            stringData:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            metadata:
              name: AWS_CREDENTIALS
              namespace: kube-system
            type: Opaque
        run: | # https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
          sudo k3s --version
          sudo mkdir --parents /var/lib/rancher/k3s/server/manifests
          sudo echo $AWS_CREDENTIALS_SECRET_RESOURCE | sudo tee /var/lib/rancher/k3s/server/manifests/aws-credentials.yaml > /dev/null
          sudo curl -o /var/lib/rancher/k3s/server/manifests/00-cert-manager-crd.yaml https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.crds.yaml
          sudo cp ./kubernetes/k3s/*.yaml /var/lib/rancher/k3s/server/manifests
          mkdir artifacts
          sudo k3s server --node-name ${{ github.run_id }}-${{ github.run_attempt }} \
          --node-label "cloud=github" \
          --tls-san $(curl ifconfig.me) > artifacts/k3s.log 2>&1 &
          until (sudo k3s kubectl get nodes); do sleep 1; done
      - id: monitor-cluster
        name: Monitor cluster for 5 minutes
        run: |
          sudo litestream replicate /var/lib/rancher/k3s/server/db/state.db s3://infrastructure.${{ env.AWS_DOMAIN_NAME }}/k3s/state.db &
          sudo k3s kubectl version --output yaml > artifacts/version.log
          sudo k3s kubectl get nodes --output yaml > artifacts/nodes.log
          sudo k3s kubectl get services --all-namespaces --output wide --watch > artifacts/services.log &
          sudo k3s kubectl get pods --all-namespaces --output wide --watch > artifacts/pods.log 2>&1 &
          sudo k3s kubectl logs deployment/metrics-server --namespace kube-system --follow > artifacts/metrics-server.log 2>&1 &
          sudo k3s kubectl get events --all-namespaces --watch > artifacts/events.log &
          sleep 300
      - id: archive-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts
