# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
# https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
name: k3s # https://github.com/k3s-io/k3s
on:
  workflow_dispatch:
    inputs: # https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context
      manual-workflow-trigger-comment:
        required: false
        default: manual workflow_dispatch triggered 
        description: comment
      force-update-cache:
        default: false
        required: false
        type: boolean
        description: force-update-cache
defaults:
  run:
    shell: bash -ex {0} # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#custom-shell
jobs:
  run-k3s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # https://github.com/actions/checkout/blob/main/action.yml
      - uses: actions/cache@v3 # https://github.com/actions/cache/blob/main/action.yml
        with:
          path: |
            /usr/local/bin/k3s
          key: k3s
      - if: steps.cache.outputs.cache-hit != 'true' || inputs.force-update-cache
        run: | # https://rancher.com/docs/k3s/latest/en/installation/install-options/
          export LATEST_STABLE_VERSION=$(curl -w '%{url_effective}' -L -s -S https://update.k3s.io/v1-release/channels/stable -o /dev/null | sed -e 's|.*/||')
          sudo curl -o /usr/local/bin/k3s -sL https://github.com/k3s-io/k3s/releases/download/${LATEST_STABLE_VERSION}/k3s
          sudo chmod +x /usr/local/bin/k3s
          sudo k3s --version
      - env: # https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
          K3S_NODE_NAME: ${{ github.run_id }}-${{ github.run_attempt }}
        run: |
          sudo k3s --version
          echo "Node name: $K3S_NODE_NAME"
          sudo mkdir --parents /var/lib/rancher/k3s/server/manifests
          sudo cp ./kubernetes/k3s/ingress-nginx-helm-chart.yaml /var/lib/rancher/k3s/server/manifests
          sudo k3s server --log k3s.log --alsologtostderr > k3s-shell.log &
          sleep 30
          sudo k3s kubectl get node --output wide
          sudo k3s kubectl get pods --all-namespaces --output wide
          sudo k3s kubectl get services --all-namespaces --output wide
          sudo k3s kubectl get ingresses --all-namespaces --output wide

        # sudo chmod +x k3s
        # sudo systemctl enable ${FILE_K3S_SERVICE}
        # sudo systemctl daemon-reload
        # sudo ./k3s server
        # ./k3s kubectl logs daemonset/metrics-server --namespace kube-system
