# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
# https://docs.github.com/en/actions/learn-github-actions/environment-variables
name: k3s # https://github.com/k3s-io/k3s https://kubernetes.io/releases/download/
on:
  workflow_dispatch:
    inputs:
      manual-workflow-comment:
        description: Manual workflow_dispatch needs at least one input parameter. Use this for comments on the reason for running the workflow manually.
        required: false
        default: Manual workflow_dispatch trigger
defaults:
  run:
    shell: bash -ex {0} # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#custom-shell
jobs:
  run-k3s:
    runs-on: ubuntu-latest
    steps:
      - id: cache
        uses: actions/cache@v3
        with:
          path: |
            /bin/k3s
          key: ${{ runner.os }}-k3s
      - if: steps.cache.outputs.cache-hit != 'true'
        run: | # https://rancher.com/docs/k3s/latest/en/installation/install-options/
          export LATEST_STABLE_VERSION=$(curl -w '%{url_effective}' -L -s -S https://update.k3s.io/v1-release/channels/stable -o /dev/null | sed -e 's|.*/||')
          curl -o k3s -sL https://github.com/k3s-io/k3s/releases/download/${LATEST_STABLE_VERSION}/k3s
          ./k3s --version
          mv k3s /bin/k3s
      - run: | # https://github.com/k3s-io/k3s/blob/master/pkg/cli/cmds/server.go https://github.com/google/cel-spec
          k3s --version
          sudo k3s server &
          sleep 30
          sudo k3s kubectl get node
        # sudo chmod +x k3s
        # sudo systemctl enable ${FILE_K3S_SERVICE}
        # sudo systemctl daemon-reload
        # sudo ./k3s server
        # ./k3s kubectl logs daemonset/metrics-server --namespace kube-system
          
          

